version: 6.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Debug

image: Visual Studio 2019 Preview

install:
  - cmd: choco install dotnetcore-sdk --pre

before_build:
  - nuget restore ICSharpCode.AvalonEdit.sln

build:
  project: ICSharpCode.AvalonEdit.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: .\packages\create_nuget.ps1
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

after_test:
  - python ICSharpCode.AvalonEdit.Tests\tidy.py
  
artifacts:
  - path: 'ICSharpCode.AvalonEdit.*.nupkg'
    name: NuGet
