version: 6.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
configuration: Debug

image: Visual Studio 2019 Preview

install:
  - cmd: choco install dotnetcore-sdk --pre
  - cmd: choco install nunit-console-runner

before_build:
  - nuget restore ICSharpCode.AvalonEdit.sln

build:
  project: ICSharpCode.AvalonEdit.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: .\packages\create_nuget.ps1

after_test:
  - python ICSharpCode.AvalonEdit.Tests\tidy.py
  
artifacts:
  - path: 'ICSharpCode.AvalonEdit.*.nupkg'
    name: NuGet
